# Домашнее задание № 5
### Выполнил: Кузнецов С.И.

# Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [2]:
N = 10  # Исходное число
result_array = np.arange(N - 1, -1, -1)
result_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
N = 10  # Исходное число

# Строим диагональную матрицу
diag_matrix = np.diag(np.arange(N, -1, -1)) 
print(diag_matrix)

# Вычисление суммы диагональных элементов
print('Сумма диагональных элементов равна {}'.format(diag_matrix.trace()))

[[10  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]
Сумма диагональных элементов равна 55


# Задание 3
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [4]:
import pandas as pd

In [5]:
# Скачиваем датасет ml-20m
ratings = pd.read_csv('ml-20m/ratings.csv', 
                      dtype = {'userId': np.int64, 'movieId': np.int64, 'rating': object, 'timestamp': np.int64}
                     )

# Находим фильм с максимальным числом оценок "5.0"
best_film = ratings[ratings.rating == '5.0'].movieId.value_counts().idxmax()
print('Больше всего оценок 5.0 было выставлено фильму c movieid = {}'.format(best_film))

Больше всего оценок 5.0 было выставлено фильму c movieid = 318


# Задание 4
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [6]:
# Скачиваем датасет
power = pd.read_csv('power.csv')

# Вычисляем суммарное потребление энергии
total_quantity = power.quantity[
    ((power['country'] == 'Latvia') | (power['country'] == 'Lithuania') | (power['country'] == 'Estonia')) &
    ((power['category'] == 4) | (power['category'] == 12) | (power['category'] == 21)) &
    (power['year'] >= 2005) & (power['year'] < 2010) &
    (power['quantity'] > 0)
].sum()

print('Суммарное потребление энергии равно {}'.format(total_quantity))

Суммарное потребление энергии равно 201719.0


# Задание 5
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [7]:
from numpy import linalg 

# Представляем систему в матричном виде: A * X = b
A = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
X = linalg.solve(A, b)

# Выводим решение
for var, val in zip(['x', 'y', 'z'], X):
    print('{} = {}'.format(var, val))

# Проверка 
if np.allclose( np.dot(A, X), b ):
    print('Решение верно')
else:
    print('Решение ошибочно')

x = 0.4666666666666668
y = 3.844444444444444
z = -5.555555555555555
Решение верно
