# Лабораторная работа
### Выполнил: Кузнецов С.И.

## Списки и строки

1. Дан произвольный список, содержащий только числа. Выведите результат сложения всех чисел больше 10.

In [1]:
import random
import re
import numpy as np

In [2]:
# Формируем исходный список случайным образом

input_list = [random.randint(-100, 100) for i in range(10)]
input_list

[-56, 0, 76, 75, 15, 53, -64, 75, -67, -70]

In [3]:
elements_more_10 = [i for i in input_list if i > 10]
if len(elements_more_10) > 0:
    print('Сумма чисел больше 10 равна {}'.format(sum(elements_more_10)))
else:
    print('В списке нет чисел больше 10.')

Сумма чисел больше 10 равна 294


2. Пусть задан список, содержащий строки. Выведите все строки, заканчивающиеся буквой r.

In [4]:
# Исходный список
list_of_strings = ['123', 'car', 'auto', 'python', 'engineer', 'WORKER', 'mobile', '']

In [5]:
# Строки, содержащие на конце 'r' (в любом регистре)
print([x for x in list_of_strings if str(x).lower().endswith('r')])

['car', 'engineer', 'WORKER']


3. Сгенерируйте и выведите cлучайную строку размером 6 символов, содержащую только цифры. Строка должна содержать хотя бы одну цифру 3.

In [6]:
num_of_pos_3 = random.randint(0, 5)  # номер элемента "3" в генерируемой строке

random_string = ''
for i in range(6):
    if i == num_of_pos_3:
        random_string += '3'
    else:
        random_string += str(random.randint(0, 9))

print('Cлучайная строка: {}'.format(random_string))        

Cлучайная строка: 469833


4. Пусть дана строка произвольной длины. Выведите информацию о том, сколько в ней символов и сколько слов.

In [7]:
# Исходная строка
input_string = 'Хлеб - всему голова.'

filtered_text = [w for w in input_string.split(' ') if re.compile('.*[А-Яа-яA-Za-z0-9].*').match(w)]

num_of_characters = len(input_string)
num_of_words = len(filtered_text)

print('В исходной строке {} символ(ов) и {} слов'.format(num_of_characters, num_of_words))

В исходной строке 20 символ(ов) и 3 слов


## Матрицы

1. Пусть дана матрица чисел размером NхN. Представьте данную матрицу в виде списка. Выведите результат сложения
всех элементов матрицы.

In [8]:
N = 5   # Размерность матрицы

# Формируем матрицу случайным образом:
matr = np.array([[random.randint(-100, 100) for j in range(N)] for i in range(N)])

print('Исходная матрица {0}x{0}:'.format(N))
print(matr)

Исходная матрица 5x5:
[[-48 -80 -50 -87 -48]
 [-74 -77   5 -71  75]
 [ 35 -38  36 -85  -6]
 [ 27 -48 -58  29  -5]
 [ -1   6 -62 -86  -9]]


In [9]:
# Преобразование матрицы в список:
matr_list =  matr.flatten()    # Список элементов матрицы

print('Список элементов матрицы:', matr_list)
#', '.join([str(i) for i in matr_list])   

Список элементов матрицы: [-48 -80 -50 -87 -48 -74 -77   5 -71  75  35 -38  36 -85  -6  27 -48 -58
  29  -5  -1   6 -62 -86  -9]


In [10]:
# Подсчет суммы элементов
print('Сумма элементов матрицы: {}'.format(sum(matr_list)))

Сумма элементов матрицы: -720


2. Пусть дана матрица чисел размером NхM. Найти столбец матрицы с максимальной суммой элементов.

In [11]:
N, M = 3, 5   # Размерность матрицы

# Формируем матрицу случайным образом:
matr = np.array([[random.randint(-100, 100) for j in range(M)] for i in range(N)])

print('Исходная матрица {}x{}:'.format(N, M))
print(matr)

Исходная матрица 3x5:
[[-17  41  46  63 -99]
 [ 81   2  31 -93  58]
 [ 13  19  -1 -62  58]]


In [12]:
# Находим столбец с максимальной суммой элементов

print('Столбец с максимальной суммой элементов: {}'.format(matr.sum(axis=0).argmax() + 1))

Столбец с максимальной суммой элементов: 1


## Работа с динамичными структурами

1. Пусть список студентов представлен в виде структуры [[No, ФИО, Возраст,Группа],[No, ФИО, Возраст, Группа],[No, ФИО,
Возраст, Группа]]. Преобразуйте список в словарь вида: {No: [ФИО, Возраст, Группа], No:[....], No: [....]}

In [13]:
# Список студентов
students = [[1, 'Иванов Иван Иванович', 20, 'M-1'],
            [2, 'Петров Петр Петрович', 25, 'M-2'],
            [3, 'Сидоров Сидор Сидорович', 23, 'M-1'],
            [4, 'Кошкин Василий Петрович', 30, 'M-3'],
            [5, 'Мышкин Петр Васильевич', 22, 'M-2']]
students

[[1, 'Иванов Иван Иванович', 20, 'M-1'],
 [2, 'Петров Петр Петрович', 25, 'M-2'],
 [3, 'Сидоров Сидор Сидорович', 23, 'M-1'],
 [4, 'Кошкин Василий Петрович', 30, 'M-3'],
 [5, 'Мышкин Петр Васильевич', 22, 'M-2']]

In [14]:
# Преобразование списка в словарь
students_dict = {s[0]: s[1:] for s in students}
students_dict

{1: ['Иванов Иван Иванович', 20, 'M-1'],
 2: ['Петров Петр Петрович', 25, 'M-2'],
 3: ['Сидоров Сидор Сидорович', 23, 'M-1'],
 4: ['Кошкин Василий Петрович', 30, 'M-3'],
 5: ['Мышкин Петр Васильевич', 22, 'M-2']}

2. Добавьте к задаче No6 для словаря возможность (без преобразования словаря обратно в список) изменить группу
студента. Поиск по «ФИО» («ФИО» студента и новый номер группы необходимо ввести с клавиатуры).

In [15]:
def change_group(stud_dict, fio, new_group):
    '''
    Изменяет группу студента с ФИО fio на new_group.
    Если студента с указанным ФИО нет, выдает предупреждение
    '''
    
    student_is_found = False   # Принимает значение True если студент найден
    for k, v in stud_dict.items():
        if v[0].lower().strip() == fio.lower().strip():
            stud_dict[k][-1] = new_group
            student_is_found = True
    
    # Предупреждение, если студент не был найден        
    if not student_is_found:
        print('WARNING! Студент с ФИО "{}" не найден'.format(fio))
    
    return None

In [16]:
change_group(stud_dict = students_dict, fio = 'Сидоров Сидор Сидорович', new_group = 'М-10')
students_dict

{1: ['Иванов Иван Иванович', 20, 'M-1'],
 2: ['Петров Петр Петрович', 25, 'M-2'],
 3: ['Сидоров Сидор Сидорович', 23, 'М-10'],
 4: ['Кошкин Василий Петрович', 30, 'M-3'],
 5: ['Мышкин Петр Васильевич', 22, 'M-2']}

3. Добавьте к задаче No6 для словаря возможность (без преобразования словаря обратно в список) изменить возраст
студента.

In [17]:
def change_age(stud_dict, fio, new_age):
    '''
    Изменяет возраст студента с ФИО fio на new_group.
    Если студента с указанным ФИО нет, выдает предупреждение
    '''
    
    student_is_found = False   # Принимает значение True если студент найден
    for k, v in stud_dict.items():
        if v[0].lower().strip() == fio.lower().strip():
            stud_dict[k][1] = new_age
            student_is_found = True
    
    # Предупреждение, если студент не был найден        
    if not student_is_found:
        print('WARNING! Студент с ФИО "{}" не найден'.format(fio))
    
    return None

In [18]:
change_age(stud_dict = students_dict, fio = 'Кошкин Василий Петрович', new_age = 35)
students_dict

{1: ['Иванов Иван Иванович', 20, 'M-1'],
 2: ['Петров Петр Петрович', 25, 'M-2'],
 3: ['Сидоров Сидор Сидорович', 23, 'М-10'],
 4: ['Кошкин Василий Петрович', 35, 'M-3'],
 5: ['Мышкин Петр Васильевич', 22, 'M-2']}